apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "7.3.7"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    adminUser: admin
    adminPassword: homelab-monitor-2026

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard

    persistence:
      enabled: true
      size: 2Gi
      storageClassName: local-path

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    service:
      type: NodePort
      nodePort: 30030

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaMetrics
            type: prometheus
            url: http://victoria-metrics-victoria-metrics-single-server:8428
            access: proxy
            isDefault: true

    extraVolumeMounts:
      - name: alerting-config
        mountPath: /etc/grafana/provisioning/alerting
    extraVolumes:
      - name: alerting-config
        configMap:
          name: redis-alerting-config
