apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-order-service
  namespace: demo-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-order-service
  template:
    metadata:
      labels:
        app: demo-order-service
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "demo-order"
        vault.hashicorp.com/agent-inject-secret-api-key: "secret/data/demo-order-service"
        vault.hashicorp.com/agent-inject-template-api-key: |
          {{- with secret "secret/data/demo-order-service" -}}
          export API_KEY={{ index .Data.data "api-key" }}
          export DB_PASSWORD={{ index .Data.data "db-password" }}
          {{- end -}}
    spec:
      serviceAccountName: demo-order-sa
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: app
          image: registry.cihuyproject.my.id/demo-order-service:latest # {"$imagepolicy": "flux-system:demo-order-service:tag"}
          command: ["/bin/sh", "-c"]
          args:
            - |
              while [ ! -f /vault/secrets/api-key ]; do sleep 0.5; done
              . /vault/secrets/api-key
              python app.py
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: APP_VERSION
              value: "1.0.0"
            - name: API_KEY_FILE
              value: "/vault/secrets/api-key"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.monitoring.svc.cluster.local:4317"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 90m
              memory: 128Mi
