apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: demo-order-service
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  update:
    strategy: Setters
    path: ./clusters/homelab/apps/demo-order
    checkout:
      branch: main
    commit:
      author:
        name: flux-automation
        email: flux@cihuylabs.my.id
      messageTemplate: "chore(demo-order): auto-update image tag to {{ .Images }}"
