apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sandbox-vs
  namespace: default
spec:
  hosts:
    - "cihuylabs.my.id"
    - "*.cihuylabs.my.id"
  gateways:
    - sandbox-gateway
  http:
    - match:
        - authority:
            prefix: portfolio.
      route:
        - destination:
            host: portfolio.portfolio.svc.cluster.local
            port:
              number: 3013
    - match:
        - authority:
            exact: cihuylabs.my.id
      route:
        - destination:
            host: cihuylabs-landing.cihuylabs-landing.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: nginx.default.svc.cluster.local
            port:
              number: 80