apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sandbox-vs
  namespace: default
spec:
  hosts:
    - "cihuylabs.my.id"
    - "*.cihuylabs.my.id"
  gateways:
    - sandbox-gateway
  http:
    - match:
        - authority:
            prefix: sandbox.
      route:
        - destination:
            host: portfolio.portfolio.svc.cluster.local
            port:
              number: 3013
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: nginx.default.svc.cluster.local
            port:
              number: 80