apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1h
  values:
    config:
      clients:
        - url: http://loki-gateway.monitoring:3100/loki/api/v1/push
      scrape_configs:
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_controller_name]
              regex: ([a-z0-9]+(?:-[a-z0-9]+)*)
              action: replace
              target_label: controller_name
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: pod
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_label_app]
              action: replace
              target_label: app
            - action: replace
              source_labels: [__meta_kubernetes_pod_node_name]
              target_label: node_name
            - action: replace
              source_labels: [__meta_kubernetes_pod_uid]
              target_label: container_runtime
          pipeline_stages:
            - cri: {}
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
