apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: quiz-vote
type: Opaque
stringData:
  POSTGRES_USER: "quizvote"
  POSTGRES_PASSWORD: "quizvote"
  POSTGRES_DB: "quizvote"
  DATABASE_URL: "postgresql://quizvote:quizvote@postgres:5432/quizvote"